/*=======================================================================
** SGI_COPYRIGHT_TAG
**=======================================================================*/
/*=======================================================================
** Author      : Paul S. Strauss (MMM yyyy)
** Modified by : Thad Beier (MMM yyyy)
**=======================================================================*/
/*=======================================================================
** VSG_COPYRIGHT_TAG
**=======================================================================*/
/*=======================================================================
** Modified by : VSG (MMM YYYY)
**=======================================================================*/


#ifndef  _SO_NODES_
#define  _SO_NODES_

#include <Inventor/nodes/SoAnnoText3.h>
#include <Inventor/nodes/SoAnnoText3Property.h>
#include <Inventor/nodes/SoAnnotation.h>
#include <Inventor/nodes/SoAntiSquish.h>
#include <Inventor/nodes/SoArray.h>
#include <Inventor/nodes/SoAsciiText.h>
#include <Inventor/nodes/SoBBox.h>
#include <Inventor/nodes/SoBackground.h>
#include <Inventor/nodes/SoBaseColor.h>
#include <Inventor/nodes/SoBaseExtrusion.h>
#include <Inventor/nodes/SoBevelProperty.h>
#include <Inventor/nodes/SoBlinker.h>
#include <Inventor/nodes/SoBufferedShape.h>
#include <Inventor/nodes/SoCallback.h>
#include <Inventor/nodes/SoCamera.h>
#include <Inventor/nodes/SoClipPlane.h>
#include <Inventor/nodes/SoColorIndex.h>
#include <Inventor/nodes/SoColorMap.h>
#include <Inventor/nodes/SoComplexity.h>
#include <Inventor/nodes/SoCone.h>
#include <Inventor/nodes/SoCoordinate3.h>
#include <Inventor/nodes/SoCoordinate4.h>
#include <Inventor/nodes/SoCSGShape.h>
#include <Inventor/nodes/SoCube.h>
#include <Inventor/nodes/SoCylinder.h>
#include <Inventor/nodes/SoDepthBuffer.h>
#include <Inventor/nodes/SoDepthOffset.h>
#include <Inventor/nodes/SoDirectionalLight.h>
#include <Inventor/nodes/SoDrawStyle.h>
#include <Inventor/nodes/SoEdgeFlag.h>
#include <Inventor/nodes/SoEnvironment.h>
#include <Inventor/nodes/SoEventCallback.h>
#include <Inventor/nodes/SoExtSelection.h>
#include <Inventor/nodes/SoExtTexture2.h>
#include <Inventor/nodes/SoExtrusion.h>
#include <Inventor/nodes/SoFaceSet.h>
#include <Inventor/nodes/SoFile.h>
#include <Inventor/nodes/SoFont.h>
#include <Inventor/nodes/SoFontStyle.h>
#include <Inventor/nodes/SoFragmentShader.h>
#include <Inventor/nodes/SoFrontBufferGroup.h>
#include <Inventor/nodes/SoFullSceneAntialiasing.h>
#include <Inventor/nodes/SoGeometryShader.h>
#include <Inventor/nodes/SoGradientBackground.h>
#include <Inventor/nodes/SoGroup.h>
#include <Inventor/nodes/SoImage.h>
#include <Inventor/nodes/SoImageBackground.h>
#include <Inventor/nodes/SoIndexedFaceSet.h>
#include <Inventor/nodes/SoIndexedLineSet.h>
#include <Inventor/nodes/SoIndexedMarkerSet.h>
#include <Inventor/nodes/SoIndexedNurbsCurve.h>
#include <Inventor/nodes/SoIndexedNurbsSurface.h>
#include <Inventor/nodes/SoIndexedPointSet.h>
#include <Inventor/nodes/SoIndexedQuadMesh.h>
#include <Inventor/nodes/SoIndexedShape.h>
#include <Inventor/nodes/SoIndexedTexture2.h>
#include <Inventor/nodes/SoIndexedTriangleSet.h>
#include <Inventor/nodes/SoIndexedTriangleStripSet.h>
#include <Inventor/nodes/SoInfo.h>
#include <Inventor/nodes/SoInteractiveComplexity.h>
#include <Inventor/nodes/SoLOD.h>
#include <Inventor/nodes/SoLabel.h>
#include <Inventor/nodes/SoLevelOfDetail.h>
#include <Inventor/nodes/SoLevelOfSimplification.h>
#include <Inventor/nodes/SoLight.h>
#include <Inventor/nodes/SoLightModel.h>
#include <Inventor/nodes/SoLineSet.h>
#include <Inventor/nodes/SoLinearProfile.h>
#include <Inventor/nodes/SoLocateHighlight.h>
#include <Inventor/nodes/SoMarker.h>
#include <Inventor/nodes/SoMarkerSet.h>
#include <Inventor/nodes/SoMaterial.h>
#include <Inventor/nodes/SoMaterialBinding.h>
#include <Inventor/nodes/SoMatrixTransform.h>
#include <Inventor/nodes/SoMultipleCopy.h>
#include <Inventor/nodes/SoNode.h>
#include <Inventor/nodes/SoNode.h>
#include <Inventor/nodes/SoNonIndexedShape.h>
#include <Inventor/nodes/SoNormal.h>
#include <Inventor/nodes/SoNormalBinding.h>
#include <Inventor/nodes/SoNurbsBoundary.h>
#include <Inventor/nodes/SoNurbsCurve.h>
#include <Inventor/nodes/SoNurbsGroup.h>
#include <Inventor/nodes/SoNurbsProfile.h>
#include <Inventor/nodes/SoNurbsProperty.h>
#include <Inventor/nodes/SoNurbsSurface.h>
#include <Inventor/nodes/SoOcclusionCulling.h>
#include <Inventor/nodes/SoOctreeOrdering.h>
#include <Inventor/nodes/SoOrthographicCamera.h>
#include <Inventor/nodes/SoPackedColor.h>
#include <Inventor/nodes/SoPathSwitch.h>
#include <Inventor/nodes/SoPattern.h>
#include <Inventor/nodes/SoPendulum.h>
#include <Inventor/nodes/SoPerspectiveCamera.h>
#include <Inventor/nodes/SoWWWInline.h>
#include <Inventor/nodes/SoCircularExtrusion.h>
#include <Inventor/nodes/SoPointLight.h>
#include <Inventor/nodes/SoPointSet.h>
#include <Inventor/nodes/SoPolygonOffset.h>
#include <Inventor/nodes/SoProfile.h>
#include <Inventor/nodes/SoProfileCoordinate2.h>
#include <Inventor/nodes/SoProfileCoordinate3.h>
#include <Inventor/nodes/SoQuadMesh.h>
#include <Inventor/nodes/SoRenderList.h>
#include <Inventor/nodes/SoRenderToTarget.h>
#include <Inventor/nodes/SoRenderToTextureProperty.h>
#include <Inventor/nodes/SoResetTransform.h>
#include <Inventor/nodes/SoRotation.h>
#include <Inventor/nodes/SoRotationXYZ.h>
#include <Inventor/nodes/SoRotor.h>
#include <Inventor/nodes/SoScale.h>
#include <Inventor/nodes/SoSelection.h>
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/nodes/SoShaderObject.h>
#include <Inventor/nodes/SoShaderParameter.h>
#include <Inventor/nodes/SoShaderProgram.h>
#include <Inventor/nodes/SoShadowGroup.h>
#include <Inventor/nodes/SoShadowStyle.h>
#include <Inventor/nodes/SoShape.h>
#include <Inventor/nodes/SoShapeHints.h>
#include <Inventor/nodes/SoShuttle.h>
#include <Inventor/nodes/SoSphere.h>
#include <Inventor/nodes/SoSpotLight.h>
#include <Inventor/nodes/SoSurroundScale.h>
#include <Inventor/nodes/SoSwitch.h>
#include <Inventor/nodes/SoText2.h>
#include <Inventor/nodes/SoText3.h>
#include <Inventor/nodes/SoTextProperty.h>
#include <Inventor/nodes/SoTexture.h>
#include <Inventor/nodes/SoTexture2.h>
#include <Inventor/nodes/SoTexture2Transform.h>
#include <Inventor/nodes/SoTexture3.h>
#include <Inventor/nodes/SoTexture3Transform.h>
#include <Inventor/nodes/SoTextureCombiner.h>
#include <Inventor/nodes/SoTextureCoordinate2.h>
#include <Inventor/nodes/SoTextureCoordinate3.h>
#include <Inventor/nodes/SoTextureCoordinateBinding.h>
#include <Inventor/nodes/SoTextureCoordinateDefault.h>
#include <Inventor/nodes/SoTextureCoordinateEnvironment.h>
#include <Inventor/nodes/SoTextureCoordinateFunction.h>
#include <Inventor/nodes/SoTextureCoordinateNormalMap.h>
#include <Inventor/nodes/SoTextureCoordinateObject.h>
#include <Inventor/nodes/SoTextureCoordinatePlane.h>
#include <Inventor/nodes/SoTextureCoordinateReflectionMap.h>
#include <Inventor/nodes/SoTextureCubeMap.h>
#include <Inventor/nodes/SoTextureMatrix.h>
#include <Inventor/nodes/SoTextureUnit.h>
#include <Inventor/nodes/SoTransform.h>
#include <Inventor/nodes/SoVertexAttribFeedback.h>
#include <Inventor/nodes/SoTransformSeparator.h>
#include <Inventor/nodes/SoTransformation.h>
#include <Inventor/nodes/SoTranslation.h>
#include <Inventor/nodes/SoTransparencyType.h>
#include <Inventor/nodes/SoTriangleSet.h>
#include <Inventor/nodes/SoTriangleStripSet.h>
#include <Inventor/nodes/SoUnits.h>
#include <Inventor/nodes/SoValueOrdering.h>
#include <Inventor/nodes/SoVertexFlag.h>
#include <Inventor/nodes/SoVertexProperty.h>
#include <Inventor/nodes/SoVertexShader.h>
#include <Inventor/nodes/SoVertexShape.h>
#include <Inventor/nodes/SoViewportClipping.h>
#include <Inventor/nodes/SoViewport.h>
#include <Inventor/nodes/SoWWWAnchor.h>
#include <Inventor/nodes/SoWWWInline.h>

#include <Inventor/VRMLnodes/SoVRMLAnchor.h>
#include <Inventor/VRMLnodes/SoVRMLAppearance.h>
#include <Inventor/VRMLnodes/SoVRMLArc2D.h>
#include <Inventor/VRMLnodes/SoVRMLArcClose2D.h>
#include <Inventor/VRMLnodes/SoVRMLAudioClip.h>
#include <Inventor/VRMLnodes/SoVRMLBackground.h>
#include <Inventor/VRMLnodes/SoVRMLBillboard.h>
#include <Inventor/VRMLnodes/SoVRMLBooleanFilter.h>
#include <Inventor/VRMLnodes/SoVRMLBooleanSequencer.h>
#include <Inventor/VRMLnodes/SoVRMLBooleanToggle.h>
#include <Inventor/VRMLnodes/SoVRMLBooleanTrigger.h>
#include <Inventor/VRMLnodes/SoVRMLBox.h>
#include <Inventor/VRMLnodes/SoVRMLCOMPONENT.h>
#include <Inventor/VRMLnodes/SoVRMLCOMPONENTDef.h>
#include <Inventor/VRMLnodes/SoVRMLCircle2D.h>
#include <Inventor/VRMLnodes/SoVRMLCollision.h>
#include <Inventor/VRMLnodes/SoVRMLColor.h>
#include <Inventor/VRMLnodes/SoVRMLColorInterpolator.h>
#include <Inventor/VRMLnodes/SoVRMLColorRGBA.h>
#include <Inventor/VRMLnodes/SoVRMLCone.h>
#include <Inventor/VRMLnodes/SoVRMLCoordinate.h>
#include <Inventor/VRMLnodes/SoVRMLCoordinateInterpolator.h>
#include <Inventor/VRMLnodes/SoVRMLCoordinateInterpolator2D.h>
#include <Inventor/VRMLnodes/SoVRMLCylinder.h>
#include <Inventor/VRMLnodes/SoVRMLCylinderSensor.h>
#include <Inventor/VRMLnodes/SoVRMLDirectionalLight.h>
#include <Inventor/VRMLnodes/SoVRMLDisk2D.h>
#include <Inventor/VRMLnodes/SoVRMLEXPORT.h>
#include <Inventor/VRMLnodes/SoVRMLEXPORTDef.h>
#include <Inventor/VRMLnodes/SoVRMLEXTERNPROTO.h>
#include <Inventor/VRMLnodes/SoVRMLEXTERNPROTODef.h>
#include <Inventor/VRMLnodes/SoVRMLEXTERNPROTOField.h>
#include <Inventor/VRMLnodes/SoVRMLEXTERNPROTOInstance.h>
#include <Inventor/VRMLnodes/SoVRMLElevationGrid.h>
#include <Inventor/VRMLnodes/SoVRMLExtrusion.h>
#include <Inventor/VRMLnodes/SoVRMLFillProperties.h>
#include <Inventor/VRMLnodes/SoVRMLFog.h>
#include <Inventor/VRMLnodes/SoVRMLFontStyle.h>
#include <Inventor/VRMLnodes/SoVRMLGeometry.h>
#include <Inventor/VRMLnodes/SoVRMLGridShape.h>
#include <Inventor/VRMLnodes/SoVRMLGroup.h>
#include <Inventor/VRMLnodes/SoVRMLIMPORT.h>
#include <Inventor/VRMLnodes/SoVRMLIMPORTDef.h>
#include <Inventor/VRMLnodes/SoVRMLISRef.h>
#include <Inventor/VRMLnodes/SoVRMLImageTexture.h>
#include <Inventor/VRMLnodes/SoVRMLIndexedFaceSet.h>
#include <Inventor/VRMLnodes/SoVRMLIndexedLine.h>
#include <Inventor/VRMLnodes/SoVRMLIndexedLineSet.h>
#include <Inventor/VRMLnodes/SoVRMLIndexedShape.h>
#include <Inventor/VRMLnodes/SoVRMLIndexedTriangleFanSet.h>
#include <Inventor/VRMLnodes/SoVRMLIndexedTriangleSet.h>
#include <Inventor/VRMLnodes/SoVRMLIndexedTriangleStripSet.h>
#include <Inventor/VRMLnodes/SoVRMLInline.h>
#include <Inventor/VRMLnodes/SoVRMLIntegerSequencer.h>
#include <Inventor/VRMLnodes/SoVRMLIntegerTrigger.h>
#include <Inventor/VRMLnodes/SoVRMLInterpOutputData.h>
#include <Inventor/VRMLnodes/SoVRMLInterpolator.h>
#include <Inventor/VRMLnodes/SoVRMLKeySensor.h>
#include <Inventor/VRMLnodes/SoVRMLLOD.h>
#include <Inventor/VRMLnodes/SoVRMLLight.h>
#include <Inventor/VRMLnodes/SoVRMLLineProperties.h>
#include <Inventor/VRMLnodes/SoVRMLLineSet.h>
#include <Inventor/VRMLnodes/SoVRMLLoadSensor.h>
#include <Inventor/VRMLnodes/SoVRMLMETA.h>
#include <Inventor/VRMLnodes/SoVRMLMETADef.h>
#include <Inventor/VRMLnodes/SoVRMLMaterial.h>
#include <Inventor/VRMLnodes/SoVRMLMetadataDouble.h>
#include <Inventor/VRMLnodes/SoVRMLMetadataFloat.h>
#include <Inventor/VRMLnodes/SoVRMLMetadataInteger.h>
#include <Inventor/VRMLnodes/SoVRMLMetadataObject.h>
#include <Inventor/VRMLnodes/SoVRMLMetadataSet.h>
#include <Inventor/VRMLnodes/SoVRMLMetadataString.h>
#include <Inventor/VRMLnodes/SoVRMLMovieTexture.h>
#include <Inventor/VRMLnodes/SoVRMLMultiTexture.h>
#include <Inventor/VRMLnodes/SoVRMLMultiTextureCoordinate.h>
#include <Inventor/VRMLnodes/SoVRMLMultiTextureTransform.h>
#include <Inventor/VRMLnodes/SoVRMLNavigationInfo.h>
#include <Inventor/VRMLnodes/SoVRMLNode.h>
#include <Inventor/VRMLnodes/SoVRMLNormal.h>
#include <Inventor/VRMLnodes/SoVRMLNormalInterpolator.h>
#include <Inventor/VRMLnodes/SoVRMLOrientationInterpolator.h>
#include <Inventor/VRMLnodes/SoVRMLOutputData.h>
#include <Inventor/VRMLnodes/SoVRMLPROFILE.h>
#include <Inventor/VRMLnodes/SoVRMLPROTO.h>
#include <Inventor/VRMLnodes/SoVRMLPROTODef.h>
#include <Inventor/VRMLnodes/SoVRMLPROTOField.h>
#include <Inventor/VRMLnodes/SoVRMLPROTOInstance.h>
#include <Inventor/VRMLnodes/SoVRMLParent.h>
#include <Inventor/VRMLnodes/SoVRMLPixelTexture.h>
#include <Inventor/VRMLnodes/SoVRMLPlaneSensor.h>
#include <Inventor/VRMLnodes/SoVRMLPointLight.h>
#include <Inventor/VRMLnodes/SoVRMLPointSet.h>
#include <Inventor/VRMLnodes/SoVRMLPolyline2D.h>
#include <Inventor/VRMLnodes/SoVRMLPolypoint2D.h>
#include <Inventor/VRMLnodes/SoVRMLPositionInterpolator.h>
#include <Inventor/VRMLnodes/SoVRMLPositionInterpolator2D.h>
#include <Inventor/VRMLnodes/SoVRMLProximitySensor.h>
#include <Inventor/VRMLnodes/SoVRMLROUTE.h>
#include <Inventor/VRMLnodes/SoVRMLROUTEDef.h>
#include <Inventor/VRMLnodes/SoVRMLRectangle2D.h>
#include <Inventor/VRMLnodes/SoVRMLScalarInterpolator.h>
#include <Inventor/VRMLnodes/SoVRMLScript.h>
#include <Inventor/VRMLnodes/SoVRMLShape.h>
#include <Inventor/VRMLnodes/SoVRMLSound.h>
#include <Inventor/VRMLnodes/SoVRMLSphere.h>
#include <Inventor/VRMLnodes/SoVRMLSphereSensor.h>
#include <Inventor/VRMLnodes/SoVRMLSpotLight.h>
#include <Inventor/VRMLnodes/SoVRMLStaticGroup.h>
#include <Inventor/VRMLnodes/SoVRMLStringSensor.h>
#include <Inventor/VRMLnodes/SoVRMLSubInterpolator.h>
#include <Inventor/VRMLnodes/SoVRMLSwitch.h>
#include <Inventor/VRMLnodes/SoVRMLTO.h>
#include <Inventor/VRMLnodes/SoVRMLText.h>
#include <Inventor/VRMLnodes/SoVRMLTexture.h>
#include <Inventor/VRMLnodes/SoVRMLTextureBackground.h>
#include <Inventor/VRMLnodes/SoVRMLTextureCoordinate.h>
#include <Inventor/VRMLnodes/SoVRMLTextureCoordinateGenerator.h>
#include <Inventor/VRMLnodes/SoVRMLTextureTransform.h>
#include <Inventor/VRMLnodes/SoVRMLTimeSensor.h>
#include <Inventor/VRMLnodes/SoVRMLTimeTrigger.h>
#include <Inventor/VRMLnodes/SoVRMLTouchSensor.h>
#include <Inventor/VRMLnodes/SoVRMLTransform.h>
#include <Inventor/VRMLnodes/SoVRMLTriangle.h>
#include <Inventor/VRMLnodes/SoVRMLTriangleFanSet.h>
#include <Inventor/VRMLnodes/SoVRMLTriangleSet.h>
#include <Inventor/VRMLnodes/SoVRMLTriangleSet2D.h>
#include <Inventor/VRMLnodes/SoVRMLTriangleStripSet.h>
#include <Inventor/VRMLnodes/SoVRMLVertexLine.h>
#include <Inventor/VRMLnodes/SoVRMLVertexPoint.h>
#include <Inventor/VRMLnodes/SoVRMLVertexShape.h>
#include <Inventor/VRMLnodes/SoVRMLViewpoint.h>
#include <Inventor/VRMLnodes/SoVRMLVisibilitySensor.h>
#include <Inventor/VRMLnodes/SoVRMLWorldInfo.h>

#include <Inventor/DirectViznodes/SoDirectVizAppearance.h>
#include <Inventor/DirectViznodes/SoDirectVizCameraShader.h>
#include <Inventor/DirectViznodes/SoDirectVizDirectionalLight.h>
#include <Inventor/DirectViznodes/SoDirectVizEnvironmentShader.h>
#include <Inventor/DirectViznodes/SoDirectVizGeneralShader.h>
#include <Inventor/DirectViznodes/SoDirectVizLightShader.h>
#include <Inventor/DirectViznodes/SoDirectVizPointLight.h>
#include <Inventor/DirectViznodes/SoDirectVizRenderingObject.h>
#include <Inventor/DirectViznodes/SoDirectVizShader.h>
#include <Inventor/DirectViznodes/SoDirectVizSpotLight.h>

// New nodes for beveling
#include <Inventor/nodes/SoEdgeFlag.h>
#include <Inventor/nodes/SoVertexFlag.h>
#include <Inventor/nodes/SoBevelProperty.h>

#include <Inventor/nodes/SoProjection.h>
#include <Inventor/nodes/SoGeoProjection.h>

#include <Inventor/nodes/SoTransformProjection.h>

// New nodes for georeferencing
#include <Inventor/geo/SoVRMLGeoCoordinate.h>
#include <Inventor/geo/SoVRMLGeoOrigin.h>
#include <Inventor/geo/SoVRMLGeoLocation.h>
#include <Inventor/geo/SoVRMLGeoElevationGrid.h>
#include <Inventor/geo/SoVRMLGeoLOD.h>
#include <Inventor/geo/SoVRMLGeoViewpoint.h>
#include <Inventor/geo/SoVRMLGeoTouchSensor.h>

#include <Inventor/geo/SoGeoCoordinate.h>
#include <Inventor/geo/SoGeoOrigin.h>
#include <Inventor/geo/SoGeoLocation.h>
#include <Inventor/geo/SoGeoElevationGrid.h>
#include <Inventor/geo/SoGeoLOD.h>
#include <Inventor/geo/SoGeoRender.h>

#endif /* _SO_NODES_ */
