/*=======================================================================
** VSG_COPYRIGHT_TAG
**=======================================================================*/
/*=======================================================================
** Author      : VSG (MMM YYYY)
**=======================================================================*/
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SoWin.rc
//
#define IDS_DOLLY                       1
#define IDS_ROTX                        2
#define IDS_ROTY                        3
#define IDS_EXAMINER_VIEWER             4
#define IDS_EXAMINER_VIEWER_PREFERENCE_SHEET 5
#define IDS_ZOOM                        6
#define IDS_STEREO_ERROR_TITLE          7
#define IDS_STEREO_ERROR                8
#define IDS_MOTION_Z                    9
#define IDS_MOTION_X                    10
#define IDS_MOTION_Y                    11
#define IDS_FLY_VIEWER                  12
#define IDS_FLY_VIEWER_PREFERENCE_SHEET 13
#define IDS_WALK_VIEWER                 14
#define IDS_WALK_VIEWER_PREFERENCE_SHEET 15
#define IDS_H                           16
#define IDS_PAN                         17
#define IDS_TILT                        18
#define IDS_PLANE_VIEWER                19
#define IDS_PLANE_VIEWER_PREFERENCE_SHEET 20
#define IDS_TRANSX                      21
#define IDS_TRANSY                      22
#define IDS_INTEN                       23
#define IDS_DIRECTIONAL_LIGHT_COLOR     24
#define IDS_DIR_LIGHT_EDITOR            25
#define IDS_MATERIAL_AMBIENT_COLOR      26
#define IDS_MATERIAL_DIFFUSE_COLOR      27
#define IDS_MATERIAL_SPECULAR_COLOR     28
#define IDS_MATERIAL_EMISSIVE_COLOR     29
#define IDS_MATERIAL                    31
#define IDS_MATERIAL_AMB                32
#define IDS_MATERIAL_DIFF               33
#define IDS_MATERIAL_SPEC               34
#define IDS_MATERIAL_EMIS               35
#define IDS_COLOR                       36
#define IDS_SLASH                       37
#define IDS_MATERIAL_EDITOR             38
#define IDS_MATERIAL_LABEL_AMB          39
#define IDS_MATERIAL_LABEL_DIFF         40
#define IDS_MATERIAL_LABEL_SPEC         41
#define IDS_MATERIAL_LABEL_EMIS         42
#define IDS_MATERIAL_LABEL_SHININESS    43
#define IDS_MATERIAL_LABEL_TRANSPARENCY 44
#define IDR_CEDT_MENU                   101
#define IDD_STEREO                      101
#define IDD_COLOR_EDITOR                102
#define IDB_CEDT_LEFT_OUT               115
#define IDB_CEDT_LEFT_UP                115
#define IDB_CEDT_LEFT_IN                116
#define IDB_CEDT_LEFT_DOWN              116
#define IDB_CEDT_RIGHT_UP               120
#define IDB_CEDT_RIGHT_DOWN             121
#define IDB_CEDT_SWITCH_UP              124
#define IDB_CEDT_SWITCH_DOWN            125
#define IDD_MATERIAL_EDITOR             125
#define IDR_MEDT_MENU                   126
#define IDD_DIR_LIGHT_EDITOR            127
#define IDR_LEDT_MENU                   127
#define IDD_MATERIAL_PALETTE            128
#define IDB_BITMAP1                     129
#define IDC_SOXT_SPIN                   130
#define IDB_BITMAP2                     131
#define IDC_SOXT_DOLLY                  131
#define IDB_BITMAP3                     132
#define IDC_SOXT_PAN                    132
#define IDB_BITMAP4                     133
#define IDC_SOXT_ROLL                   133
#define IDB_BITMAP5                     134
#define IDC_SOXT_SEEK                   134
#define IDB_BITMAP6                     135
#define IDC_SOXT_VIEWING                135
#define IDB_BITMAP7                     136
#define IDC_SOXT_UPVEC                  136
#define IDB_BITMAP8                     137
#define IDB_BITMAP9                     138
#define IDB_BITMAP10                    139
#define IDB_BITMAP11                    140
#define IDI_FRED                        141
#define IDB_PUSH_PICK                   142
#define IDB_PUSH_VIEW                   143
#define IDB_PUSH_HELP                   144
#define IDB_PUSH_HOME                   145
#define IDB_PUSH_SETHOME                146
#define IDB_PUSH_VIEWALL                147
#define IDB_PUSH_SEEK                   148
#define IDB_PUSH_ORTHO                  149
#define IDB_PUSH_PERSP                  150
#define IDB_PUSH_BIGX                   151
#define IDB_PUSH_BIGY                   152
#define IDB_PUSH_BIGZ                   153
#define IDB_PUSH_GRAYSEEK               154
#define IDM_MAINPOPUP                   155
#define IDM_MAINPOPUP_EXAMVWR           156
#define IDD_FILE_PATH_BROWSER           156
#define IDR_MEDT_MENU1                  157
#define IDC_SOXT_VIEW_WALK              157
#define IDC_CLASSIC_WALK_CURSOR         158
#define IDC_CLASSIC_PAN_CURSOR          159
#define IDC_CLASSIC_ROLL_CURSOR         160
#define IDC_CLASSIC_SEEK_CURSOR         161
#define IDC_CLASSIC_SPIN_CURSOR         162
#define IDC_CLASSIC_UP_CURSOR           163
#define IDC_CLASSIC_FLY_CURSOR          164
#define IDC_CLASSIC_DOLLY_CURSOR        165
#define IDC_SHADOW_WALK_CURSOR          166
#define IDC_SHADOW_PAN_CURSOR           167
#define IDC_SHADOW_ROLL_CURSOR          168
#define IDC_SHADOW_SEEK_CURSOR          169
#define IDC_SHADOW_SPIN_CURSOR          170
#define IDC_SHADOW_UP_CURSOR            171
#define IDC_SHADOW_FLY_CURSOR           172
#define IDC_SHADOW_DOLLY_CURSOR         173
#define IDC_XOR_WALK_CURSOR             174
#define IDC_XOR_PAN_CURSOR              175
#define IDC_XOR_ROLL_CURSOR             176
#define IDC_XOR_SEEK_CURSOR             177
#define IDC_XOR_SPIN_CURSOR             178
#define IDC_XOR_UP_CURSOR               179
#define IDC_XOR_FLY_CURSOR              180
#define IDC_XOR_DOLLY_CURSOR            181
#define ID_MPOPUP_VIEWING               197
#define IDS_MATERIAL_PALETTE_WIDTH      226
#define IDS_STEREO_DIALOG               227
#define IDD_CONSERROR_DIALOG            228
#define IDC_CEDT_SLIDER0                1000
#define IDC_CEDT_SLIDER1                1001
#define IDC_CEDT_EDIT0                  1002
#define IDC_CEDT_EDIT1                  1004
#define IDC_CEDT_SLIDER2                1006
#define IDC_CEDT_EDIT2                  1007
#define IDC_CEDT_SLIDER3                1009
#define IDC_CEDT_EDIT3                  1010
#define IDC_CEDT_SLIDER4                1012
#define IDC_CEDT_EDIT4                  1013
#define IDC_CEDT_SLIDER5                1015
#define IDC_CEDT_EDIT5                  1016
#define IDC_CEDT_COLORWHEEL             1018
#define IDC_CEDT_RIGHT                  1020
#define IDC_CEDT_SWITCH                 1022
#define IDC_CEDT_LEFT                   1023
#define IDC_CEDT_ACCEPT                 1029
#define IDC_CEDT_PATCH0                 1038
#define IDC_CEDT_PATCH1                 1039
#define IDC_CEDT_STATIC0                1041
#define IDC_CEDT_STATIC1                1042
#define IDC_CEDT_STATIC2                1043
#define IDC_CEDT_STATIC3                1044
#define IDC_CEDT_STATIC4                1045
#define IDC_CEDT_STATIC5                1046
#define IDC_CEDT_AREA0                  1048
#define IDC_MEDT_SLIDER0                1049
#define IDC_CEDT_AREA1                  1050
#define IDC_MEDT_SLIDER1                1050
#define IDC_CEDT_AREA2                  1051
#define IDC_MEDT_SLIDER2                1051
#define IDC_CEDT_AREA3                  1052
#define IDC_MEDT_SLIDER3                1052
#define IDC_CEDT_AREA4                  1053
#define IDC_MEDT_SLIDER4                1053
#define IDC_MEDT_SLIDER5                1054
#define IDC_MEDT_EDIT0                  1055
#define IDC_MEDT_EDIT1                  1056
#define IDC_MEDT_EDIT2                  1057
#define IDC_MEDT_EDIT3                  1058
#define IDC_MEDT_EDIT4                  1059
#define IDC_MEDT_EDIT5                  1060
#define IDC_MEDT_STATIC0                1061
#define IDC_MEDT_STATIC1                1062
#define IDC_MEDT_STATIC2                1063
#define IDC_MEDT_STATIC3                1064
#define IDC_MEDT_STATIC4                1065
#define IDC_MEDT_RADIOR0                1066
#define IDC_MEDT_RADIOL0                1067
#define IDC_MEDT_RADIOR1                1068
#define IDC_MEDT_RADIOL1                1069
#define IDC_MEDT_RADIOR2                1070
#define IDC_MEDT_RADIOL2                1071
#define IDC_MEDT_RADIOR3                1072
#define IDC_MEDT_RADIOL3                1073
#define IDC_MEDT_STATIC6                1074
#define IDC_MEDT_RA                     1075
#define IDC_MEDT_ACCEPT                 1076
#define IDC_LEDT_RA                     1077
#define IDC_LEDT_SLIDER0                1078
#define IDC_LEDT_STATIC0                1079
#define IDC_LEDT_EDIT0                  1080
#define IDC_MAT_PAL_RA                  1082
#define ID_SET_BROWSE_PATH              1082
#define ID_CANCEL_BROWSE_PATH           1083
#define IDC_MATERIAL_PATH               1084
#define IDC_STATUS                      1085
#define IDC_PALETTE_NAME                1086
#define IDC_COMBO_STEREO                1086
#define IDC_CHECK_REVERT_STEREO         1088
#define IDC_STEREO_SLIDER2              1089
#define IDC_STEREO_SLIDER1              1090
#define IDC_CHECK_STEREO                1091
#define IDC_EDIT_CONSERROR              1092
#define IDC_CLOSE_CONSERROR             1093
#define IDC_CLEAR_CONSERROR             1094
#define IDC_SAVE_CONSERROR              1098
#define IDM_CEDT_CONTINUOUS             40001
#define IDM_CEDT_MANUAL                 40002
#define IDM_CEDT_WYSIWYG                40003
#define IDM_CEDT_COPY                   40004
#define IDM_CEDT_PASTE                  40005
#define IDM_CEDT_HELP                   40006
#define IDM_CEDT_NONE                   40007
#define IDM_CEDT_VALUE                  40008
#define IDM_CEDT_RGB                    40009
#define IDM_CEDT_HSV                    40010
#define IDM_CEDT_RGBV                   40011
#define IDM_CEDT_RGBHSV                 40012
#define IDM_MEDT_MATERIALLIST           40013
#define IDM_MEDT_CONTINUOUS             40014
#define IDM_MEDT_MANUAL                 40015
#define IDM_MEDT_COPY                   40016
#define IDM_MEDT_PASTE                  40017
#define IDM_MEDT_HELP                   40018
#define IDM_LEDT_COLOR_EDITOR           40019
#define IDM_LEDT_COPY                   40020
#define IDM_LEDT_PASTE                  40021
#define IDM_LEDT_HELP                   40022
#define IDM_MPOPUP_VIEWING              40023
#define IDM_MPOPUP_DECORAT              40024
#define IDM_MPOPUP_HLIGHT               40025
#define IDM_FPOPUP_HOME                 40026
#define IDM_FPOPUP_SETHOME              40027
#define IDM_FPOPUP_VIEWALL              40028
#define IDM_FPOPUP_SEEK                 40029
#define IDM_DPOPUP_ASIS                 40030
#define IDM_DPOPUP_HLINE                40031
#define IDM_DPOPUP_NOTEX                40032
#define IDM_DPOPUP_LOWRES               40033
#define IDM_DPOPUP_WIRE                 40034
#define IDM_DPOPUP_POINTS               40035
#define IDM_DPOPUP_BBOX                 40036
#define IDM_DPOPUP_MSAMEAS              40037
#define IDM_DPOPUP_MHLINE               40038
#define IDM_DPOPUP_MLOWRES              40039
#define IDM_DPOPUP_MWIRE                40040
#define IDM_DPOPUP_MPOINTS              40041
#define IDM_DPOPUP_MBBOX                40042
#define IDM_DPOPUP_SBUFFER              40043
#define IDM_DPOPUP_DBUFFER              40044
#define IDM_DPOPUP_IBUFFER              40045
#define IDM_PPOPUP_SEEK                 40046
#define IDM_PPOPUP_CLIP                 40047
#define IDM_PPOPUP_SPIN                 40048
#define IDM_PPOPUP_AXES                 40049
#define IDM_DPOPUP_MNOTEX               40050
#define IDM_MEDT_MATERIALPALETTE        40052
#define ID_MATERIAL_PATH                40054
#define ID_PALETTE_WINDOWS              40055
#define IDM_PPOPUP_STEREO               40055
#define ID_EDIT_COLOR                   40056
#define ID_WINDOW_ALWAYSONTOP           40057
#define ID_EDIT_MATERIAL                40058
#define IDM_EDIT_COPY                   40060
#define IDM_MPOPUP_FULLSCREEN           40062
#define IDM_MPOPUP_OPENRT				        40077
#define IDM_PPOPUP_FSAA                 40078
#define IDM_PPOPUP_RECORD               40083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         40084
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SoWin.rc
//
#define IDS_DOLLY                       1
#define IDS_ROTX                        2
#define IDS_ROTY                        3
#define IDS_EXAMINER_VIEWER             4
#define IDS_EXAMINER_VIEWER_PREFERENCE_SHEET 5
#define IDS_ZOOM                        6
#define IDS_STEREO_ERROR_TITLE          7
#define IDS_STEREO_ERROR                8
#define IDS_MOTION_Z                    9
#define IDS_MOTION_X                    10
#define IDS_MOTION_Y                    11
#define IDS_FLY_VIEWER                  12
#define IDS_FLY_VIEWER_PREFERENCE_SHEET 13
#define IDS_WALK_VIEWER                 14
#define IDS_WALK_VIEWER_PREFERENCE_SHEET 15
#define IDS_H                           16
#define IDS_PAN                         17
#define IDS_TILT                        18
#define IDS_PLANE_VIEWER                19
#define IDS_PLANE_VIEWER_PREFERENCE_SHEET 20
#define IDS_TRANSX                      21
#define IDS_TRANSY                      22
#define IDS_INTEN                       23
#define IDS_DIRECTIONAL_LIGHT_COLOR     24
#define IDS_DIR_LIGHT_EDITOR            25
#define IDS_MATERIAL_AMBIENT_COLOR      26
#define IDS_MATERIAL_DIFFUSE_COLOR      27
#define IDS_MATERIAL_SPECULAR_COLOR     28
#define IDS_MATERIAL_EMISSIVE_COLOR     29
#define IDS_MATERIAL                    31
#define IDS_MATERIAL_AMB                32
#define IDS_MATERIAL_DIFF               33
#define IDS_MATERIAL_SPEC               34
#define IDS_MATERIAL_EMIS               35
#define IDS_COLOR                       36
#define IDS_SLASH                       37
#define IDS_MATERIAL_EDITOR             38
#define IDS_MATERIAL_LABEL_AMB          39
#define IDS_MATERIAL_LABEL_DIFF         40
#define IDS_MATERIAL_LABEL_SPEC         41
#define IDS_MATERIAL_LABEL_EMIS         42
#define IDS_MATERIAL_LABEL_SHININESS    43
#define IDS_MATERIAL_LABEL_TRANSPARENCY 44
#define IDR_CEDT_MENU                   101
#define IDD_STEREO                      101
#define IDD_COLOR_EDITOR                102
#define IDB_CEDT_LEFT_OUT               115
#define IDB_CEDT_LEFT_UP                115
#define IDB_CEDT_LEFT_IN                116
#define IDB_CEDT_LEFT_DOWN              116
#define IDB_CEDT_RIGHT_UP               120
#define IDB_CEDT_RIGHT_DOWN             121
#define IDB_CEDT_SWITCH_UP              124
#define IDB_CEDT_SWITCH_DOWN            125
#define IDD_MATERIAL_EDITOR             125
#define IDR_MEDT_MENU                   126
#define IDD_DIR_LIGHT_EDITOR            127
#define IDR_LEDT_MENU                   127
#define IDD_MATERIAL_PALETTE            128
#define IDB_BITMAP1                     129
#define IDC_SOXT_SPIN                   130
#define IDB_BITMAP2                     131
#define IDC_SOXT_DOLLY                  131
#define IDB_BITMAP3                     132
#define IDC_SOXT_PAN                    132
#define IDB_BITMAP4                     133
#define IDC_SOXT_ROLL                   133
#define IDB_BITMAP5                     134
#define IDC_SOXT_SEEK                   134
#define IDB_BITMAP6                     135
#define IDC_SOXT_VIEWING                135
#define IDB_BITMAP7                     136
#define IDC_SOXT_UPVEC                  136
#define IDB_BITMAP8                     137
#define IDB_BITMAP9                     138
#define IDB_BITMAP10                    139
#define IDB_BITMAP11                    140
#define IDI_FRED                        141
#define IDB_PUSH_PICK                   142
#define IDB_PUSH_VIEW                   143
#define IDB_PUSH_HELP                   144
#define IDB_PUSH_HOME                   145
#define IDB_PUSH_SETHOME                146
#define IDB_PUSH_VIEWALL                147
#define IDB_PUSH_SEEK                   148
#define IDB_PUSH_ORTHO                  149
#define IDB_PUSH_PERSP                  150
#define IDB_PUSH_BIGX                   151
#define IDB_PUSH_BIGY                   152
#define IDB_PUSH_BIGZ                   153
#define IDM_MAINPOPUP                   155
#define IDM_MAINPOPUP_EXAMVWR           156
#define IDD_FILE_PATH_BROWSER           156
#define IDR_MEDT_MENU1                  157
#define IDC_SOXT_VIEW_WALK              157
#define IDC_CLASSIC_WALK_CURSOR         158
#define IDC_CLASSIC_PAN_CURSOR          159
#define IDC_CLASSIC_ROLL_CURSOR         160
#define IDC_CLASSIC_SEEK_CURSOR         161
#define IDC_CLASSIC_SPIN_CURSOR         162
#define IDC_CLASSIC_UP_CURSOR           163
#define IDC_CLASSIC_FLY_CURSOR          164
#define IDC_CLASSIC_DOLLY_CURSOR        165
#define IDC_SHADOW_WALK_CURSOR          166
#define IDC_SHADOW_PAN_CURSOR           167
#define IDC_SHADOW_ROLL_CURSOR          168
#define IDC_SHADOW_SEEK_CURSOR          169
#define IDC_SHADOW_SPIN_CURSOR          170
#define IDC_SHADOW_UP_CURSOR            171
#define IDC_SHADOW_FLY_CURSOR           172
#define IDC_SHADOW_DOLLY_CURSOR         173
#define IDC_XOR_WALK_CURSOR             174
#define IDC_XOR_PAN_CURSOR              175
#define IDC_XOR_ROLL_CURSOR             176
#define IDC_XOR_SEEK_CURSOR             177
#define IDC_XOR_SPIN_CURSOR             178
#define IDC_XOR_UP_CURSOR               179
#define IDC_XOR_FLY_CURSOR              180
#define IDC_XOR_DOLLY_CURSOR            181
#define ID_MPOPUP_VIEWING               197
#define IDS_MATERIAL_PALETTE_WIDTH      226
#define IDS_STEREO_DIALOG               227
#define IDD_CONSERROR_DIALOG            228
#define IDC_CEDT_SLIDER0                1000
#define IDC_CEDT_SLIDER1                1001
#define IDC_CEDT_EDIT0                  1002
#define IDC_CEDT_EDIT1                  1004
#define IDC_CEDT_SLIDER2                1006
#define IDC_CEDT_EDIT2                  1007
#define IDC_CEDT_SLIDER3                1009
#define IDC_CEDT_EDIT3                  1010
#define IDC_CEDT_SLIDER4                1012
#define IDC_CEDT_EDIT4                  1013
#define IDC_CEDT_SLIDER5                1015
#define IDC_CEDT_EDIT5                  1016
#define IDC_CEDT_COLORWHEEL             1018
#define IDC_CEDT_RIGHT                  1020
#define IDC_CEDT_SWITCH                 1022
#define IDC_CEDT_LEFT                   1023
#define IDC_CEDT_ACCEPT                 1029
#define IDC_CEDT_PATCH0                 1038
#define IDC_CEDT_PATCH1                 1039
#define IDC_CEDT_STATIC0                1041
#define IDC_CEDT_STATIC1                1042
#define IDC_CEDT_STATIC2                1043
#define IDC_CEDT_STATIC3                1044
#define IDC_CEDT_STATIC4                1045
#define IDC_CEDT_STATIC5                1046
#define IDC_CEDT_AREA0                  1048
#define IDC_MEDT_SLIDER0                1049
#define IDC_CEDT_AREA1                  1050
#define IDC_MEDT_SLIDER1                1050
#define IDC_CEDT_AREA2                  1051
#define IDC_MEDT_SLIDER2                1051
#define IDC_CEDT_AREA3                  1052
#define IDC_MEDT_SLIDER3                1052
#define IDC_CEDT_AREA4                  1053
#define IDC_MEDT_SLIDER4                1053
#define IDC_MEDT_SLIDER5                1054
#define IDC_MEDT_EDIT0                  1055
#define IDC_MEDT_EDIT1                  1056
#define IDC_MEDT_EDIT2                  1057
#define IDC_MEDT_EDIT3                  1058
#define IDC_MEDT_EDIT4                  1059
#define IDC_MEDT_EDIT5                  1060
#define IDC_MEDT_STATIC0                1061
#define IDC_MEDT_STATIC1                1062
#define IDC_MEDT_STATIC2                1063
#define IDC_MEDT_STATIC3                1064
#define IDC_MEDT_STATIC4                1065
#define IDC_MEDT_RADIOR0                1066
#define IDC_MEDT_RADIOL0                1067
#define IDC_MEDT_RADIOR1                1068
#define IDC_MEDT_RADIOL1                1069
#define IDC_MEDT_RADIOR2                1070
#define IDC_MEDT_RADIOL2                1071
#define IDC_MEDT_RADIOR3                1072
#define IDC_MEDT_RADIOL3                1073
#define IDC_MEDT_STATIC6                1074
#define IDC_MEDT_RA                     1075
#define IDC_MEDT_ACCEPT                 1076
#define IDC_LEDT_RA                     1077
#define IDC_LEDT_SLIDER0                1078
#define IDC_LEDT_STATIC0                1079
#define IDC_LEDT_EDIT0                  1080
#define IDC_MAT_PAL_RA                  1082
#define ID_SET_BROWSE_PATH              1082
#define ID_CANCEL_BROWSE_PATH           1083
#define IDC_MATERIAL_PATH               1084
#define IDC_STATUS                      1085
#define IDC_PALETTE_NAME                1086
#define IDC_COMBO_STEREO                1086
#define IDC_CHECK_REVERT_STEREO         1088
#define IDC_STEREO_SLIDER2              1089
#define IDC_STEREO_SLIDER1              1090
#define IDC_CHECK_STEREO                1091
#define IDC_EDIT_CONSERROR              1092
#define IDC_CLOSE_CONSERROR             1093
#define IDC_CLEAR_CONSERROR             1094
#define IDC_CHECK_CAMERA                1095
#define IDC_CHECK_PARALLAX              1096
#define IDC_EDIT_CAMERA                 1102
#define IDC_EDIT_PARALLAX               1103
#define IDM_CEDT_CONTINUOUS             40001
#define IDM_CEDT_MANUAL                 40002
#define IDM_CEDT_WYSIWYG                40003
#define IDM_CEDT_COPY                   40004
#define IDM_CEDT_PASTE                  40005
#define IDM_CEDT_HELP                   40006
#define IDM_CEDT_NONE                   40007
#define IDM_CEDT_VALUE                  40008
#define IDM_CEDT_RGB                    40009
#define IDM_CEDT_HSV                    40010
#define IDM_CEDT_RGBV                   40011
#define IDM_CEDT_RGBHSV                 40012
#define IDM_MEDT_MATERIALLIST           40013
#define IDM_MEDT_CONTINUOUS             40014
#define IDM_MEDT_MANUAL                 40015
#define IDM_MEDT_COPY                   40016
#define IDM_MEDT_PASTE                  40017
#define IDM_MEDT_HELP                   40018
#define IDM_LEDT_COLOR_EDITOR           40019
#define IDM_LEDT_COPY                   40020
#define IDM_LEDT_PASTE                  40021
#define IDM_LEDT_HELP                   40022
#define IDM_MPOPUP_VIEWING              40023
#define IDM_MPOPUP_DECORAT              40024
#define IDM_MPOPUP_HLIGHT               40025
#define IDM_FPOPUP_HOME                 40026
#define IDM_FPOPUP_SETHOME              40027
#define IDM_FPOPUP_VIEWALL              40028
#define IDM_FPOPUP_SEEK                 40029
#define IDM_DPOPUP_ASIS                 40030
#define IDM_DPOPUP_HLINE                40031
#define IDM_DPOPUP_NOTEX                40032
#define IDM_DPOPUP_LOWRES               40033
#define IDM_DPOPUP_WIRE                 40034
#define IDM_DPOPUP_POINTS               40035
#define IDM_DPOPUP_BBOX                 40036
#define IDM_DPOPUP_MSAMEAS              40037
#define IDM_DPOPUP_MHLINE               40038
#define IDM_DPOPUP_MLOWRES              40039
#define IDM_DPOPUP_MWIRE                40040
#define IDM_DPOPUP_MPOINTS              40041
#define IDM_DPOPUP_MBBOX                40042
#define IDM_DPOPUP_SBUFFER              40043
#define IDM_DPOPUP_DBUFFER              40044
#define IDM_DPOPUP_IBUFFER              40045
#define IDM_PPOPUP_SEEK                 40046
#define IDM_PPOPUP_CLIP                 40047
#define IDM_PPOPUP_SPIN                 40048
#define IDM_PPOPUP_AXES                 40049
#define IDM_DPOPUP_MNOTEX               40050
#define IDM_MEDT_MATERIALPALETTE        40052
#define ID_MATERIAL_PATH                40054
#define ID_PALETTE_WINDOWS              40055
#define IDM_PPOPUP_STEREO               40055
#define ID_EDIT_COLOR                   40056
#define ID_WINDOW_ALWAYSONTOP           40057
#define ID_EDIT_MATERIAL                40058
#define IDM_EDIT_COPY                   40060
#define IDM_MPOPUP_FULLSCREEN           40062
#define IDM_PPOPUP_FSAA                 40078
#define IDM_PPOPUP_RECORD               40083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         40084
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
