/*====================  CONTAINERS ============================= */
#if defined(_WIN32)
#pragma warning( push )
#pragma warning( disable: 4702 )  // unreachable code warning generated by STL
#endif

#ifdef _WIN32 // To disable warnings about STL templates
//#  if !defined(_DEBUG)
//#    undef _SECURE_SCL
//#    define _SECURE_SCL 0
//#  endif
#  define OIV_STL_STD
#endif

#ifdef OIV_STL_VECTOR
#include <vector>
#endif

#ifdef OIV_STL_SET
#include <set>
#endif

#ifdef OIV_STL_HASH_SET
#include <hash_set>
#endif

#ifdef OIV_STL_DEQUE 
#include <deque>
#endif

#ifdef OIV_STL_LIST 
#include <list>
#endif

#ifdef OIV_STL_MAP 
#include <map>
#endif

#ifdef OIV_STL_HASH_MAP 
#include <hash_map>
#endif

#ifdef OIV_STL_QUEUE 
#include <queue>
#endif

#ifdef OIV_STL_STACK 
#include <stack>
#endif

#ifdef OIV_STL_BITSET 
#include <bitset>
#endif

#ifdef OIV_STL_STRING 
#include <string>
#endif

#ifdef OIV_STL_VALARRAY 
#include <valarray>
#endif

#ifdef OIV_STL_ITERATOR 
#include <iterator>
#endif

/*====================  MISC ================================= */
#ifdef OIV_STL_ALGORITHM 
#include <algorithm>
#endif

#ifdef OIV_STL_LIMITS 
#include <limits>
#endif

#ifdef OIV_STL_NUMERIC 
#include <numeric>
#endif

#ifdef OIV_STL_FUNCTIONAL 
#include <functional>
#endif

#ifdef OIV_STL_LOCALE 
#include <locale>
#endif

#ifdef OIV_STL_MEMORY 
#include <memory>
#endif

#ifdef OIV_STL_UTILITY 
#include <utility>
#endif

#ifdef OIV_STL_COMPLEX 
#include <complex>
#endif

#ifdef OIV_STL_CASSERT 
#include <cassert>
#endif

/*====================  EXCEPTIONS =========================== */
#ifdef OIV_STL_STDEXCEPT 
#include <stdexcept>
#endif

#ifdef OIV_STL_EXCEPTION 
#include <exception>
#endif

/*====================  IO =================================== */
#ifdef OIV_STL_FSTREAM 
#include <fstream>
#endif

#ifdef OIV_STL_IOMANIP 
#include <iomanip>
#endif

#ifdef OIV_STL_IOS 
#include <ios>
#endif

#ifdef OIV_STL_IOSFWD 
#include <iosfwd>
#endif

#ifdef OIV_STL_IOSTREAM 
#include <iostream>
#endif

#ifdef OIV_STL_ISTREAM 
#include <istream>
#endif

#ifdef OIV_STL_OSTREAM 
#include <ostream>
#endif

#ifdef OIV_STL_SSTREAM 
#include <sstream>
#endif

#ifdef OIV_STL_STRSTREAM 
#include <strstream>
#endif

#ifdef OIV_STL_STREAMBUF 
#include <streambuf>
#endif

#if defined(_WIN32)
#pragma warning( pop )
#endif

